package ch.conceptforge.mavenprojecthibernatetuto;
// Generated 26 mars 2018 07:36:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private Integer id;
     private Client client;
     private String nomcde;
     private Date datecde;

    public Commande() {
    }

    public Commande(Client client, String nomcde, Date datecde) {
       this.client = client;
       this.nomcde = nomcde;
       this.datecde = datecde;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getNomcde() {
        return this.nomcde;
    }
    
    public void setNomcde(String nomcde) {
        this.nomcde = nomcde;
    }
    public Date getDatecde() {
        return this.datecde;
    }
    
    public void setDatecde(Date datecde) {
        this.datecde = datecde;
    }




}


