package ch.conceptforge.mavenprojecthibernatetuto;
// Generated 23 mars 2018 15:40:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private Integer id;
     private String nomcde;
     private int idclient;
     private Date datecde;

    public Commande() {
    }

    public Commande(String nomcde, int idclient, Date datecde) {
       this.nomcde = nomcde;
       this.idclient = idclient;
       this.datecde = datecde;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomcde() {
        return this.nomcde;
    }
    
    public void setNomcde(String nomcde) {
        this.nomcde = nomcde;
    }
    public int getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(int idclient) {
        this.idclient = idclient;
    }
    public Date getDatecde() {
        return this.datecde;
    }
    
    public void setDatecde(Date datecde) {
        this.datecde = datecde;
    }




}


